const webpush = require('web-push');

const pushKeys = {
  subject: 'mailto:malcolm.keeweesiong@gmail.com',
  publicKey: 'asdf', // publicKey and privateKey to be generated by generate-keys.js
  privateKey: 'wxyz'
};

// subscription is the data service worker registration pushManager subscribe returned
const subscription = {
  endpoint: 'https://fcm.googleapis.com/fcm/send/asdfasdf',
  expirationTime: null,
  keys: {
    p256dh: 'asdf',
    auth: 'asdf'
  }
};

const message = 'show-notification';

webpush.setVapidDetails(
  pushKeys.subject,
  pushKeys.publicKey,
  pushKeys.privateKey
);

webpush
  .sendNotification(subscription, message)
  .then(function() {
    console.log('message sent!');
  })
  .catch(function() {
    console.log('message failed to sent!');
  });
